### ISSUE TITLE
Image in readme?

### ISSUE THREAD

**Issue by kevinlinxc** [sxysxy/OIDN-python#1]
Could you add a before and after in the readme for a denoising example? Also, do you know if the performance is worse for noise reduction for images that weren't made via rendering?

**Comment by sxysxy** [comment]
OK, it's a good advice. I know it is for images rendered by something like Monte-Carlo PathTracer, I am amateur in physical based rendering

**Comment by sxysxy** [comment]
Example images added in readme.

**Comment by sxysxy** [comment]
Thank u for this issue.
